version: '3.7'

services:
  main:
    image: node:19
    environment:
      PORT: 3000
      ENVIRONMENT: local
      LOG_LEVEL: info
      MONGODB_URL: mongodb://admin:admin@mongo:27017
    stdin_open: true
    tty: true
    ports: ['3000:3000']
    command: './node_modules/.bin/ts-node-dev --transpile-only --exit-child src/index.ts'
    depends_on: [ mongo ]

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports: [ '27017:27017' ]

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017
