version: '3.7'

services:
  main:
    image: alamonall/thegooddoctor
    environment:
      PORT: 3000
      API_PORT: 3001
      ENVIRONMENT: local
      LOG_LEVEL: info
      MONGODB_URL: mongodb://admin:admin@mongo:27017
      DB_NAME: hospital
      REDIS_URI: redis://redis:6379
    stdin_open: true
    tty: true
    volumes:
      - .:/code
    working_dir: /code
    ports: ['3001:3001']
    depends_on: [ mongo, mongo-express, redis ]

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports: [ '27017:27017' ]

  redis: 
    image: redis:alpine3.17
    ports: 
      - 6379:6379
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017
